### ISSUE TITLE
VM release

### ISSUE THREAD

**Issue by osmo-guy** [bastienbaranoff/imsi-catcher#1]
Hello Bastian,

unfortunatley I couldnt find your email adress.
First I wanted to ask if you are out of the hospital :) and second if there is a possibility to create an VM for that excellent project you did: https://www.youtube.com/watch?v=mK9NA_s-vHs
Please let me know, how we/I can encourage you to release a VM like that.
Unfortuatley your tutorial on https://bastienbaranoff.wordpress.com/2016/02/08/gsm-base-station-with-two-osmocom-bb-compatible-phones-on-kali-rolling/ wasnt so trivial. It seemed to have errors while building asterisk and is only possible on Kali 2.0.

Thanks in advance, I would be happy for any response of yours.

Best regards,
Alex

**Comment by bastienbaranoff** [comment]
I will update my blog and I work on the VM right now it's near the end. Glad you like my work.

**Comment by osmo-guy** [comment]
Salut Bastien,

great to hear from you, I will follow your blog and cant wait until your done with it.

Best regards,
Alex

**Comment by bastienbaranoff** [comment]
you can email me at bastienbaranoff@gmail.com

**Comment by bastienbaranoff** [comment]
VM done and working will upload today surely...

**Comment by bastienbaranoff** [comment]
Prebuilt VM https://drive.google.com/open?id=0B8txqiSyAFMtQVJYZWduMXYxZkU
